# Generated by Django 3.0.3 on 2020-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_diary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
